name: B

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_run:
    workflows: ["A"]
    types: 
      - completed
      
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: echo 'foo'
        
  bar:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: B
        run: echo 'B'
