name: "example-cron-action2"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Get package update date
        run: |
         updated_at=$(curl -L -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/users/${{ github.repository_owner }}/packages/container/aptypo.io  | jq -r .updated_at)
         updated_at_timestamp=$(date -d $updated_at +"%s")
         echo 'UPDATED_AT='$updated_at_timestamp >> $GITHUB_ENV    
      - name: Get Tetris package update date
        run: |
         tetris_updated_at=$(curl -L -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/users/${{ github.repository_owner }}/packages/container/react-tetris  | jq -r .updated_at)
         tetris_updated_at_timestamp=$(date -d $tetris_updated_at +"%s")
         echo 'TETRIS_UPDATED_AT='$tetris_updated_at_timestamp >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: bar
        env:
          AWS_CONTAINER_NAME: ${{ secrets.AWS_CONTAINER_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SERVICE_NAME: ${{ secrets.AWS_SERVICE_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_IMAGE_URL: ghcr.io/aptypo/aptypo.io:main
        run: |
          json=$(envsubst < .github/workflows/lightsail-create-container-service-deployment.json)
          echo $json > .github/workflows/lightsail-create-container-service-deployment.json
          echo $(cat .github/workflows/lightsail-create-container-service-deployment.json)
          aws lightsail create-container-service-deployment --region $AWS_REGION --cli-input-json file://.github/workflows/lightsail-create-container-service-deployment.json
      - name: foo
        if: ${{ env.TETRIS_UPDATED_AT > env.UPDATED_AT }}
        run: |
          echo 1
