name: "example-cron-action2"
on:
  schedule:
    - cron:  '*/10000 * * * *'    # At every 15th minute

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: |
         TETRIS_INFO=$(curl -L -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/users/${{ github.repository_owner }}/packages/container/react-tetris)
         echo $TETRIS_INFO
      - run: echo $TETRIS_INFO
      - run: echo 1
      - run: echo 2
