name: "example-cron-action2"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: get Tetris update date
        run: |
         tetris_updated_at=$(curl -L -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/users/${{ github.repository_owner }}/packages/container/react-tetris  | jq .updated_at)
         echo $tetris_updated_at
         echo 'TETRIS_UPDATED_AT='$tetris_updated_at >> $GITHUB_ENV
         echo $TETRIS_UPDATED_AT
         echo $(date -d $tetris_updated_at +"%s")
