name: "example-cron-action"
on:
  schedule:
    - cron:  '*/1 * * * *'    # At every 15th minute

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: TETRIS_INFO=$(curl -L -H "Authorization: Bearer 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" https://api.github.com/users/aptypo/packages/container/react-tetris)
      - run: echo $TETRIS_INFO
